# Generated by Django 4.0.4 on 2022-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
